# Generated by Django 2.1.7 on 2019-10-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiRequestCount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apirequest',
            name='requests',
        ),
    ]
